ERROR 2024-07-16 14:51:15,611 log 21104 25532 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\car_backend_Aether\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2024-07-16 14:51:15,613 basehttp 21104 25532 "GET /accounts/login/?next=/ HTTP/1.1" 500 90577
WARNING 2024-08-06 15:23:21,051 log 27984 56664 Not Found: /static/drf-yasg/style.css
WARNING 2024-08-06 15:23:21,052 log 27984 56420 Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
WARNING 2024-08-06 15:23:21,054 log 27984 47188 Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
WARNING 2024-08-06 15:23:21,054 basehttp 27984 56664 "GET /static/drf-yasg/style.css HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,055 basehttp 27984 56420 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,056 basehttp 27984 47188 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,058 log 27984 56664 Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
WARNING 2024-08-06 15:23:21,060 log 27984 56420 Not Found: /static/drf-yasg/insQ.min.js
WARNING 2024-08-06 15:23:21,061 log 27984 47188 Not Found: /static/drf-yasg/immutable.min.js
WARNING 2024-08-06 15:23:21,062 basehttp 27984 56664 "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,062 basehttp 27984 56420 "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,062 basehttp 27984 47188 "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,064 log 27984 56664 Not Found: /static/drf-yasg/style.css
WARNING 2024-08-06 15:23:21,064 basehttp 27984 56664 "GET /static/drf-yasg/style.css HTTP/1.1" 404 179
WARNING 2024-08-06 15:23:21,070 log 27984 47188 Not Found: /static/drf-yasg/swagger-ui-init.js
WARNING 2024-08-06 15:23:21,070 basehttp 27984 47188 "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 404 179
ERROR 2024-08-06 15:23:27,910 log 41424 50352 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\Aether-Car\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2024-08-06 15:23:27,913 basehttp 41424 50352 "GET /accounts/login/?next=/ HTTP/1.1" 500 90562
WARNING 2024-08-06 15:23:28,205 log 41424 50352 Not Found: /favicon.ico
WARNING 2024-08-06 15:23:28,206 basehttp 41424 50352 "GET /favicon.ico HTTP/1.1" 404 3349
